# Generated by Django 4.1.4 on 2022-12-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('md_display', '0003_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='research/images/'),
        ),
    ]
